import 'dotenv/config';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'openai/gpt-oss-120b:free';

/**
 * Sends a structured prompt to the OpenRouter LLM.
 * @param {string} systemPrompt 
 * @param {string} userMessage 
 * @returns {Promise<string>} - The LLM's text response.
 */
export async function fetchLlmResponse(systemPrompt, userMessage) {
    if (!process.env.OPENROUTER_API_KEY) {
        throw new Error('OPENROUTER_API_KEY is not set.');
    }

    const payload = {
        model: MODEL,
        messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userMessage }
        ],
        temperature: 0.1, // Keep standard behavior focused on context
    };

    try {
        const response = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
                // Optional tracking headers for OpenRouter
                'HTTP-Referer': 'http://localhost:3000',
                'X-Title': 'College Chatbot Backend',
            },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('OpenRouter Error:', errorText);
            throw new Error(`OpenRouter returned status ${response.status}`);
        }

        const data = await response.json();

        // Extract textual text content from choices
        if (data.choices && data.choices.length > 0) {
            return data.choices[0].message.content;
        }
        return "I'm sorry, no answer was generated by the LLM.";
    } catch (error) {
        console.error('Error calling OpenRouter:', error);
        throw error;
    }
}
